### ISSUE TITLE
Recursive msgpack2json with maps

### ISSUE THREAD

**Issue by xor-gate** [ludocode/msgpack-tools#4]
Hi Nicolas,

I'm using the msgpack2json tool to convert a messagepack logfile to json. 
How the file is formatted (where every map is a log record):

```
<map>5 key-values</map>
<map>5 key-values</map>...... many more
```

Currently the tool only converts the first map and then stops. I know it is not valid JSON but is it possible to fetch all the maps until the file is done (and all map records are converted)?

**Comment by ludocode** [comment]
Yes, this is definitely something it should do. I originally had it expecting exactly one element (a JSON "document"), but JSON doesn't even have the concept of a document anymore, and I added support for hooking it up to a stream for RPC-type stuff so it really doesn't make sense for it to only convert one element.

I'll fix it.

**Comment by rpodgorny** [comment]
time for a release, perhaps? i'm also waiting for this feature. thanks... ;-)

**Comment by ludocode** [comment]
Fixed on develop. I'm putting together a 0.6 release now.

**Comment by xor-gate** [comment]
Great, nice to see you again :=)
